<?php

namespace Core\Settings\Requests;

use Core\Company\Models\Address;
use Illuminate\Foundation\Http\FormRequest;

class AddressRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth(ADMIN_GUARD)->check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return $this->getRules();
    }


    /**
     * invalid messages
     *
     * @return array
     * @author Wesam
     */
    public function messages()
    {
        return [
            'title.*.required_without_all' => trans('Auth::validation.required_without_all'),
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * get rules accordin' to the chosen
     *  address type
     * @return array
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     * @author Amr
     */
    private function getRules()
    {
        $class = address_type_map()[$this->request->get('address_type')['value']['hash']];
        if ($class == Address::class)
            return array_merge($class::$rules, [
                'owner_type.id' => 'required',
                'owner.id' => 'required',
            ]);
        return $class::$rules;
    }

}
