<?php

namespace Core\Settings\Requests;

use App\Image;
use Illuminate\Foundation\Http\FormRequest;

class CountryRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return auth(SUPER_ADMIN_GUARD)->check();
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $rules = [];
        foreach (locales() as $i => $locale) {
            $rules['name.' . $locale] = 'required_without_all:' . attributesByLocale('name', $locale) . ',' . null;
            $rules['nationality.' . $locale] = 'required_without_all:' . attributesByLocale('nationality', $locale) . ',' . null;
        }
        $rules = array_merge($rules, [
            'postal_code' => 'required|regex:/\b\d{5}\b/',
            'mobile_prefix' => 'required',
            'currency_id' => 'required',
            'language_id' => 'required',
//            'flag' => Image::$rules
        ]);
        return $rules;
    }


    /**
     * invalid messages
     *
     * @return array
     * @author Wesam
     */
    public function messages()
    {
        return [
            'title.*.required_without_all' => trans('Auth::validation.required_without_all'),
        ]; // TODO: Change the autogenerated stub
    }

}
