<?php

namespace Core\Subscription\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StorePlanOfferRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {

        $rules = [];
        foreach (locales() as $i => $locale) {
            $rules['title.' . $locale] = 'required_without_all:'.attributesByLocale('title',$locale).',' . null;
        }
        $rules = array_merge($rules, [
            'plan_id'=> 'required|exists:plans,id',
            'starts_at' => 'required|before:ends_at',
            'ends_at' => 'required|after:starts_at',
            'discount_percentage_per_year' => 'required|numeric|max:100',
            'discount_percentage_per_month' => 'required|numeric|max:100',
        ]);

        return $rules;
    }

    public function messages()
    {
        return [
            'title.*.required_without_all' => trans('Auth::validation.required_without_all'),
        ]; // TODO: Change the autogenerated stub
    }
}
